---

- name: remove sshkey
  action: shell rm {{ sshkey_path }}/sshkey
  ignore_errors: true
  when:
    - usr_pwd == "sshkey"

- name: remove sshkey.pub
  action: shell rm {{ sshkey_path }}/sshkey.pub
  ignore_errors: true
  when:
    - usr_pwd == "sshkey"


- name: generate sshkey
  action: shell yes | ssh-keygen -b 2048 -t rsa -f {{ sshkey_path }}/sshkey -q -N "" && cat {{ sshkey_path }}/sshkey.pub
  register: ssh_pub_key
  when:
    - usr_pwd == "sshkey"

- set_fact: ssh_pub_key={{ ssh_pub_key.stdout }}
  when:
    - usr_pwd == "sshkey"

- name: generate sshkey
  action: shell cat {{ sshkey_path }}/sshkey
  register: ssh_pvt_key
  when:
    - usr_pwd == "sshkey"

- set_fact: ssh_pvt_key={{ ssh_pvt_key.stdout }}
  when:
    - usr_pwd == "sshkey"

- name: generate password
  action: shell date +%s | sha256sum | base64 | head -c 16 ; echo
  register: generated_usr_pwd
  when:
    - usr_pwd == "generate" or usr_pwd == "sshkey"

- set_fact: text_usr_pwd={{ generated_usr_pwd.stdout }}
  when:
    - usr_pwd == "generate" or usr_pwd == "sshkey"


- name: generate ldap admin password hash
  command: "/usr/sbin/slappasswd -s {{ text_usr_pwd }}"
  register: slapd_admin_password_hash

- name: add the user
  ldap_entry:
    dn: uid={{ user_name }},{{ usr_base_dn }}
    objectClass:
      - shadowAccount
      - person
      - organizationalPerson
      - inetOrgPerson
      - posixAccount
      - top
      - ldapPublicKey
    attributes:
      loginShell: "{{ login_shell }}"
      description: An sftp user
#      userPassword: "{MD5}{{ usr_pwd|hash('md5') }}"
      userPassword: "{{ slapd_admin_password_hash.stdout }}"
      sn: "{{ surname }}"
      cn: "{{ user_name }}"
      gidNumber: "{{ usr_gid }}"
      homeDirectory: "{{sftp_home_partition}}/{{ user_name }}"
      uidNumber: "{{ uid }}"
    server_uri: "{{ ldap_server_uri }}"
    bind_dn: "{{ bind_dn }}"
    bind_pw: "{{ bind_pw }}"

- name: Add ssh key ids
  ldap_attr:
    dn: uid={{ user_name }},{{ "ou="employee_type,usr_base_dn }}
    name: "sshPublicKey"
    values: "{{ ssh_pub_key }}"
    state: present
    server_uri: "{{ ldap_server_uri }}"
    bind_dn: "{{ bind_dn }}"
    bind_pw: "{{ bind_pw }}"
  when:
    - usr_pwd == "sshkey"
