---
- name: add the user
  ldap_entry:
    dn: uid={{ user_name }},{{ usr_base_dn }}
    objectClass:
      - shadowAccount
      - person
      - organizationalPerson
      - inetOrgPerson
      - posixAccount
      - top
    attributes:
      loginShell: "{{ login_shell }}"
      description: An sftp user
      userPassword: "{{ usr_pwd | hash('sha1') }}"
      sn: "{{ surname }}"
      cn: "{{ user_name }}"
      gidNumber: "{{ gid }}"
      homeDirectory: "{{sftp_home_partition}}/{{ user_name }}"
      uidNumber: "{{ uid }}"
    server_uri: "{{ ldap_server_uri }}"
    bind_dn: "{{ bind_dn }}"
    bind_pw: "{{ bind_pw }}"