- debug: msg={{ gid }}
- name: add a group
  ldap_entry:
    dn: cn={{ group_name }},{{ grp_base_dn }}
    objectClass:
      - posixGroup
      - top
    attributes:
      cn: "{{ group_name }}"
      gidNumber: "{{ gid }}"
    server_uri: "{{ ldap_server_uri }}"
    bind_dn: "{{ bind_dn }}"
    bind_pw: "{{ bind_pw }}"

- name: Add member ids
  ldap_attr:
    dn: cn={{ group_name }},{{ grp_base_dn }}
    name: "memberUid"
    values: "{{ item }}"
    state: present
    server_uri: "{{ ldap_server_uri }}"
    bind_dn: "{{ bind_dn }}"
    bind_pw: "{{ bind_pw }}"
  with_items:
    - "{{ group_users }}"
