---
- name: Get uid
  shell: awk -F "=" '/uid/ {print $2}' {{ config_file_path }}/Details.ini | tr -d ' '
  register: uidData

- set_fact: uid={{ uidData.stdout | int + 1  }}

- debug: msg={{ uid }}

- ini_file:
    path: "{{ config_file_path }}/Details.ini"
    section: ldap
    option: uid
    value: "{{ uid }}"
    backup: no