- name: Check whether group exist
  action: shell getent group {{ user_name }}
  register: group_exist
  ignore_errors: true
  when:
    - task == "add"

- name: Check whether user exist
  action: shell /usr/bin/getent passwd {{ user_name }}
  register: user_exist
  ignore_errors: true
  when:
    - task == "add"


- include: roles/ldap/tasks/get_gid.yml
  when:
    - task == "add"
    - group_exist.stdout == ""

- include: roles/ldap/tasks/add_group.yml
  when:
    - task == "add"
    - group_exist.stdout == ""


- include: roles/ldap/tasks/get_uid.yml
  when:
    - task == "add"
    - group_exist.stdout == ""

- include: roles/ldap/tasks/add_users.yml
  when:
    - task == "add"
    - group_exist.stdout == ""


- include: roles/ldap/tasks/delete_user.yml
  when:
    - task == "delete"

- include: roles/ldap/tasks/delete_group.yml
  when:
    - task == "delete"


#- debug:
#    msg: "user already exist in the system please use another username and try again"
#  when:
#    - user_exist.stdout != ""