---
- name: sftp-playbook | Test sftp-server role
  hosts: phantom
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
      - vars/ftp_automation_vars.yml
  roles:
    #- ldap
    - sftp
    - email