---
- debug: var={{ sftp_config }}
# Create directories for individual SFTP users. Optional.
- name: SFTP-Server | Create directories per user
  file:
    path: "{{ sftp_home_partition }}/{{ user_name }}/{{ item | default(default_dir) }}"
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: "{{ dir_mode  | default(0750) }}"
    state: directory
  with_items:
    - "{{ sftp_directories }}"