# A working chrooted SFTP setup requires root:sftgroup ownership of a user's home directory.
- name: SFTP-Server | Correct ownership and permission of home directories
  file:
    path: "{{ sftp_home_partition }}/{{ user_name }}"
    owner: root
    group: "{{ group_name }}"
    mode: "{{ dir_mode }}"