# Necessary for chrooting of SFTP users.
- name: SFTP-Server | Alter sftp subsystem entry
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Subsystem(\s+)sftp'
    line: "Subsystem sftp internal-sftp"
    state: present
  notify: SFTP-Server | Restart sshd


- name: SFTP-Server | Add sshd_config block
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: '# {mark} SFTP-Server block'
    block:
      Match Group {{ group_name }}
          ChrootDirectory {{ sftp_home_partition }}/{{ user_name }}
          AllowTCPForwarding no
          X11Forwarding no
          ForceCommand internal-sftp
  notify: SFTP-Server | Restart sshd

#- name: SFTP-Server | Add sshd_config block
#  action: shell echo " Match Group {{ user_name }}
#                               ChrootDirectory {{ sftp_home_partition }}/{{ user_name }}
#                               AllowTCPForwarding no
#                               X11Forwarding no
#                               ForceCommand internal-sftp " >> /etc/ssh/sshd_config
#  notify: SFTP-Server | Restart sshd
