---
sshd_port: 22
sshd_permit_root_login: 'no'
sshd_password_authentication: 'yes'
sshd_x11_forwarding: 'no'
sshd_allow_tcp_forwarding: 'no'
sshd_client_alive_count_max: 2
sshd_compression: "no"
sshd_log_facility: "AUTHPRIV"
sshd_log_level: "VERBOSE"
sshd_max_sessions: 2
sshd_use_dns: "no"
sshd_allow_agent_forwarding: "no"
sshd_tcp_keep_alive: "no"
# if need sftp then sftp_only_enabled xor sftp_enabled
sshd_sftp_only_enabled: no
sshd_sftp_enabled: no
