- name: get deploy path
  set_fact: destination="/var/lib/docker/workspace/{{ deploy_server }}/html/OHRMStandalone/{{ deploy_location|upper }}/{{ deploy_name }}-{{ deploy_location }}-{{ deploy_server }}.orangehrm.com"

- debug: msg={{ destination }}

- name: create folder
  command: "cd /var/lib/docker/workspace/{{ deploy_server }}/html/OHRMStandalone/{{ deploy_location|upper }} && mkdir {{ deploy_name }}-{{ deploy_location }}-{{ deploy_server }}.orangehrm.com"

- name: copy build from ftp location
  copy:
    remote_src: True
    src: "{{ build_location }}"
    force: "no"
    dest: "{{ destination }}/build.zip"
