- name: (Ubuntu) add repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ debian_version }} main
    update_cache: yes
    state: present
  tags: [docker]

- name: (Ubuntu) application is present
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]

- name: (Ubuntu) service is enabled in reboot
  command: systemctl enable docker
  tags: [docker]